// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXn0PuCG9zHrJxc5Dq4w_Vc55zSvzISK8',
    appId: '1:783570633573:web:59006dc80ecb960547978c',
    messagingSenderId: '783570633573',
    projectId: 'mindmateproject-8d210',
    authDomain: 'mindmateproject-8d210.firebaseapp.com',
    storageBucket: 'mindmateproject-8d210.firebasestorage.app',
    measurementId: 'G-3WD9KR1XZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8MZ13-iHBg7c0RJWWpEU4rua18zEXWJ4',
    appId: '1:783570633573:android:a5a73d24dc5852a847978c',
    messagingSenderId: '783570633573',
    projectId: 'mindmateproject-8d210',
    storageBucket: 'mindmateproject-8d210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4RnagnUYWuY7a8Zj5NIHhzFPGAoTzY70',
    appId: '1:783570633573:ios:49a90c0ced830fb647978c',
    messagingSenderId: '783570633573',
    projectId: 'mindmateproject-8d210',
    storageBucket: 'mindmateproject-8d210.firebasestorage.app',
    iosBundleId: 'com.example.mindMateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4RnagnUYWuY7a8Zj5NIHhzFPGAoTzY70',
    appId: '1:783570633573:ios:49a90c0ced830fb647978c',
    messagingSenderId: '783570633573',
    projectId: 'mindmateproject-8d210',
    storageBucket: 'mindmateproject-8d210.firebasestorage.app',
    iosBundleId: 'com.example.mindMateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXn0PuCG9zHrJxc5Dq4w_Vc55zSvzISK8',
    appId: '1:783570633573:web:0555a0a1e5b9087147978c',
    messagingSenderId: '783570633573',
    projectId: 'mindmateproject-8d210',
    authDomain: 'mindmateproject-8d210.firebaseapp.com',
    storageBucket: 'mindmateproject-8d210.firebasestorage.app',
    measurementId: 'G-GZMFF8JK71',
  );
}
